apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana-dash-provider
  namespace: monitoring
data:
  providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /var/lib/grafana/dashboards

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana-datasources-provider
  namespace: monitoring
data:
  providers.yaml: |
    apiVersion: 1
    datasources:
    - name: 'prometheus'
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-service:8080
      isDefault: true
      editable: false