secretGenerator:
  - name: gcp-credentials
    type: Opaque
    files:
      - key.json=010-gcp.credentials.secret.json
  - name: jwt
    type: Opaque
    files:
      - key=030-jwt-key.secret.txt
  - name: x-auth
    type: Opaque
    files:
      - token=040-x-auth-token.secret.txt

generatorOptions:
  disableNameSuffixHash: true
