apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  template:
    spec:
      containers:
        - name: broker
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              memory: 1Gi
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx1G"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
  namespace: kafka
spec:
  template:
    spec:
      containers:
        - name: zookeeper
          resources:
            requests:
              cpu: 10m
              memory: 384Mi
            limits:
              memory: 512Mi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
  namespace: kafka
spec:
  template:
    spec:
      containers:
        - name: zookeeper
          resources:
            requests:
              cpu: 10m
              memory: 384Mi
            limits:
              memory: 512Mi
