lowercaseOutputName: true
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
ssl: false
whitelistObjectNames: ["kafka.server:*","kafka.controller:*","kafka.producer:*","kafka.consumer:*","java.lang:*"]